baseURL = "http://example.org/"
languageCode = "en-us"
title = "Awesome Inc"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
[module]
    [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"